import { COMPANY_NAME } from '@/constant';
import { ImageCarousel } from 'components/ImageCarousel';
import Head from 'next/head';

// TODO: Improve SEO
const Home = () => {
  const images = ['/Phone2.jpg', '/Phone4.jpg'];

  return (
    <>
      <Head>
        <title>{COMPANY_NAME}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/logo.svg"
        />
      </Head>
      <ImageCarousel
        autoPlay
        images={images}
      />
    </>
  );
};

export default Home;
