import { getAllContentFiles, getAllProducts } from 'api/shopify';
import { DesignGrid } from 'components/DesignGrid';
import { QueryKey } from '@/interface';
import Head from 'next/head';
import { dehydrate, QueryClient, useQuery } from 'react-query';
import { Container } from '@mui/material';
import { COMPANY_NAME } from '@/constant';

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();
  await Promise.all([
    queryClient.prefetchQuery([QueryKey.PhoneCase], () => getAllProducts()),
    queryClient.prefetchQuery([QueryKey.ContentFile], () =>
      getAllContentFiles()
    ),
  ]);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

const PhoneCases = () => {
  const { data: products } = useQuery({
    queryKey: [QueryKey.PhoneCase],
    queryFn: () => getAllProducts(),
  });
  const { data: designs } = useQuery({
    queryKey: [QueryKey.ContentFile],
    queryFn: () => getAllContentFiles(),
  });

  return (
    <>
      <Head>
        <title>{COMPANY_NAME}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/logo.svg"
        />
      </Head>
      <Container>
        <DesignGrid designs={designs} />
      </Container>
    </>
  );
};

export default PhoneCases;
