import { COMPANY_NAME } from '@/constant';
import Head from 'next/head';

const ContactUs = () => {
  return (
    <>
      <Head>
        <title>{COMPANY_NAME}</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/logo.svg"
        />
      </Head>
    </>
  );
};

export default ContactUs;
